world_name: "aspa135_m3"
origin:
    latitude: -66.28223056
    longitude: 110.53892500
    altitude: 30.19

drones:
  - model_type: "quadrotor_base"
    model_name: "drone0"
    flight_time: 60
    xyz:
      - 7.00
      - 8.00
      - 32.10
    payload:
      - model_type: "gps"
        model_name: "gps"

  - model_type: "quadrotor_base"
    model_name: "drone1"
    flight_time: 60
    xyz:
      - 4.00
      - 4.00
      - 32.50
    payload:
      - model_type: "gps"
        model_name: "gps"

  - model_type: "quadrotor_base"
    model_name: "drone2"
    flight_time: 60
    xyz:
      - 4.00
      - 8.00
      - 32.60
    payload:
      - model_type: "gps"
        model_name: "gps"

  - model_type: "quadrotor_base"
    model_name: "drone3"
    flight_time: 60
    xyz:
      - 7.00
      - 4.00
      - 32.70
    payload:
      - model_type: "gps"
        model_name: "gps"
