world_name: "aspa135_m3"
origin: 
    latitude: -66.28223056
    longitude: 110.53892500
    altitude: 30.19

drones:
  - model_type: "quadrotor_base"
    model_name: "drone0"
    flight_time: 60
    xyz:
      - 5.05
      - 3.24
      - 32.31
    payload:
      - model_type: "gps"
        model_name: "gps"

  - model_type: "quadrotor_base"
    model_name: "drone1"
    flight_time: 60
    xyz:
      - 5.65
      - 6.10
      - 32.09
    payload:
      - model_type: "gps"
        model_name: "gps"